import { User } from "../../entities/User.js";

export const userCompleteList: User[] = [
  {
    id: "0",
    username: "John Doe",
    email: "johndoe@gmail.com",
    createdAt: new Date("16/01/2022"),
    password: "password",
    updatedAt: new Date("21/02/2023"),
    bio: "call me john",
  },
  {
    id: "1",
    username: "Jane Smith",
    email: "janesmith@gmail.com",
    createdAt: new Date("12/04/2021"),
    password: "password123",
    updatedAt: new Date("02/03/2023"),
    bio: "I love hiking and traveling!",
  },
  {
    id: "2",
    username: "Mike Johnson",
    email: "mikejohnson@gmail.com",
    createdAt: new Date("07/12/2020"),
    password: "password456",
    updatedAt: new Date("09/03/2023"),
    bio: "Tech enthusiast and coffee addict ☕️",
  },
  {
    id: "3",
    username: "Sara Lee",
    email: "saralee@gmail.com",
    createdAt: new Date("01/05/2019"),
    password: "password789",
    updatedAt: new Date("05/03/2023"),
    bio: "Dog lover and beach enthusiast 🐶🏖",
  },
  {
    id: "4",
    username: "David Kim",
    email: "davidkim@gmail.com",
    createdAt: new Date("16/09/2020"),
    password: "password101",
    updatedAt: new Date("08/03/2023"),
    bio: "I love playing video games and watching movies 🎮🎥",
  },
  {
    id: "5",
    username: "Emily Wong",
    email: "emilywong@gmail.com",
    createdAt: new Date("29/02/2020"),
    password: "password202",
    updatedAt: new Date("03/03/2023"),
    bio: "Coffee addict and book lover ☕️📚",
  },
  {
    id: "6",
    username: "Tom Wilson",
    email: "tomwilson@gmail.com",
    createdAt: new Date("11/06/2021"),
    password: "password303",
    updatedAt: new Date("06/03/2023"),
    bio: "I love hiking and exploring new places!",
  },
];
